2020/09/09 15:33:22 [1;34m[I] [service.go:257] [8f15d82587bd7b63] login to server success, get run id [8f15d82587bd7b63], server udp port [0][0m
2020/09/09 15:33:22 [1;34m[I] [proxy_manager.go:144] [8f15d82587bd7b63] proxy added: [prometheus hublle-ui traefic-admin jaeger k8s ex-lb transport grafana][0m
2020/09/09 15:33:22 [1;34m[I] [control.go:179] [8f15d82587bd7b63] [k8s] start proxy success[0m
2020/09/09 15:33:22 [1;34m[I] [control.go:179] [8f15d82587bd7b63] [prometheus] start proxy success[0m
2020/09/09 15:33:22 [1;34m[I] [control.go:179] [8f15d82587bd7b63] [ex-lb transport] start proxy success[0m
2020/09/09 15:33:22 [1;34m[I] [control.go:179] [8f15d82587bd7b63] [jaeger] start proxy success[0m
2020/09/09 15:33:22 [1;34m[I] [control.go:179] [8f15d82587bd7b63] [grafana] start proxy success[0m
2020/09/09 15:33:22 [1;34m[I] [control.go:179] [8f15d82587bd7b63] [traefic-admin] start proxy success[0m
2020/09/09 15:33:22 [1;34m[I] [control.go:179] [8f15d82587bd7b63] [hublle-ui] start proxy success[0m
2020/09/09 15:33:25 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:26 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:27 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:28 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:29 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:30 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:31 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:32 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:33 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:34 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:34 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:35 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:36 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:37 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:38 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:39 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:40 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:41 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:42 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:43 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:43 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:44 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:45 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:46 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:47 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:48 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:49 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:50 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:51 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:52 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:52 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:53 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:54 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:55 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:56 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:57 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:58 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:33:59 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:34:00 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:34:01 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:34:01 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:34:02 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:34:03 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:34:04 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:34:05 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:34:06 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:34:07 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:34:08 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:34:09 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
2020/09/09 15:34:10 [1;31m[E] [proxy.go:615] [8f15d82587bd7b63] [k8s] connect to local service [10.0.0.252:6443] error: dial tcp 10.0.0.252:6443: connect: connection refused[0m
